databases:
  - name: tamaade-db
    databaseName: tamaade
    user: tamaade_user

  - name: tamaade-redis
    type: redis

services:
  - type: web
    name: tamaade-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "sh -lc \"gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --log-level debug --access-logfile - --error-logfile -\""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamaade-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: tamaade-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.2
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: PORT
        value: "8000"

  - type: worker
    name: tamaade-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A config worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamaade-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: tamaade-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: tamaade-redis
          property: connectionString
      - key: REDIS_BACKEND
        fromDatabase:
          name: tamaade-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.2
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
